name: uihub_basic_bottom_sheet
description: "free flutter ui is all you need"
#publish_to: 'none'
repository: https://github.com/flutter-uihub/uihub_basic_bottom_sheet

version: 1.0.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  june_flow_util:
  modal_bottom_sheet:
  styled_widget:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/uihub/uihub_basic_bottom_sheet/
  uses-material-design: true

topics:
  - uihub